### ISSUE TITLE
Práctica 10.- Contador

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/Destello_Movil#4]
[Práctica 10 - Contador-Edwin_Yanet_Carlos_Jeronima..pdf](https://github.com/user-attachments/files/18092538/Practica.10.-.Contador-Edwin_Yanet_Carlos_Jeronima.pdf)

**Comment by ka194** [comment]
Portada y escudos institucionales: 25 puntos
Descripción detallada del procedimiento: 25 puntos
Incluye ilustraciones: 25 puntos
Resultado y conclusión: 25 puntos
Porcentaje obtenido 100% = 50 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
